### ISSUE TITLE
ContextFactory Cache Error

### ISSUE THREAD

**Issue by arcadeindy** [yswenli/SAEA#1]
1. Setting Websocker server max count = 2 and cache = true
2. When Client 1 and Client 2 connect to server => Everything Work.
3. After Client 1 and Client 2 disconnected from server.
4. Client 3, 4, 5 try to connect to server => Everything Failed.

Maybe UserToken cannot reuse from ContextFactory. because when i setting cache = false => Result is work good.

**Comment by yswenli** [comment]
I see what you mean, because of the complexity of the SocketAsyncEventArgs model, UserToken hasn't found a suitable way to cache yet. There is a problem in SocketAsyncEventArgs that this instance of SocketAsyncEventArgs cannot be reused when UserToken is not empty. So I've reconstructed the cache block later.
